use std::{
    cell::{Cell, RefCell},
    collections::HashMap,
    fmt::Debug,
    future::Future,
    marker::PhantomData,
    rc::Rc,
    sync::Arc,
};

use leptos::{either::Either, ev, prelude::*};
use leptos_router::{
    ChooseView, MatchInterface, MatchNestedRoutes, MatchParams, NavigateOptions, NestedRoute,
    PathSegment, PossibleRouteMatch, SsrMode, StaticSegment,
    components::*,
    hooks::{use_location, use_navigate},
    location::Location,
};

use leptos_i18n::{I18nContext, Locale, use_i18n_context};

// this whole file is a hack into `leptos_router`, it absolutely should'nt be used like that, but eh I'm a professional (or not.)

#[derive(Debug)]
struct PathBuilder<'a>(Vec<&'a str>);

impl Default for PathBuilder<'_> {
    fn default() -> Self {
        Self::new()
    }
}

impl<'a> PathBuilder<'a> {
    pub fn new() -> Self {
        PathBuilder(vec![""])
    }

    pub fn extend<I>(&mut self, iter: I)
    where
        I: IntoIterator<Item = &'a str>,
    {
        for seg in iter {
            self.push(seg);
        }
    }

    pub fn push(&mut self, s: &'a str) {
        let s = s.trim_matches('/');
        if !s.is_empty() {
            self.0.push(s);
        }
    }

    pub fn build(&self) -> String {
        let s = self.0.join("/");
        if s.is_empty() { "/".to_owned() } else { s }
    }
}

/// Where the dynamic segments of a route are found in a path it matches.
#[derive(Debug, Default)]
struct LocalizedPathMatch {
    /// Path segment index captured by each `OptionalParam` of the route, in route order,
    /// `None` when the optional param is absent from the path.
    optionals: Vec<Option<usize>>,
    /// Path segment index captured by each `Param` of the route, in route order.
    params: Vec<usize>,
    /// Index of the first path segment captured by the `Splat` of the route.
    splat: usize,
}

/// Match a path, already split in segments, against a route generated by `leptos_router`.
fn match_path_segments(
    segments: &[&str],
    old_segments: &[PathSegment],
) -> Option<LocalizedPathMatch> {
    fn inner(
        segments: &[&str],
        seg_idx: usize,
        route: &[PathSegment],
    ) -> Option<LocalizedPathMatch> {
        let Some((next_seg, route)) = route.split_first() else {
            // The route is exhausted, it's a match only if the path is too.
            return segments.is_empty().then(|| LocalizedPathMatch {
                splat: seg_idx,
                ..Default::default()
            });
        };

        match next_seg {
            // Zero width segments, they consume nothing.
            // An empty static is emitted by the `I18nRoute` base route.
            PathSegment::Unit => inner(segments, seg_idx, route),
            PathSegment::Static(to_match) if to_match.is_empty() => inner(segments, seg_idx, route),
            PathSegment::Static(to_match) => {
                let (seg, segments) = segments.split_first()?;
                (to_match == seg).then_some(())?;
                inner(segments, seg_idx + 1, route)
            }
            PathSegment::Param(_) => {
                let (_, segments) = segments.split_first()?;
                let mut matches = inner(segments, seg_idx + 1, route)?;
                matches.params.insert(0, seg_idx);
                Some(matches)
            }
            // An optional param captures any segment, or is absent, exactly as `leptos_router`
            // expands it into both variants. Try to capture first, and fall back to absent.
            PathSegment::OptionalParam(_) => segments
                .split_first()
                .and_then(|(_, segments)| inner(segments, seg_idx + 1, route))
                .map(|mut matches| {
                    matches.optionals.insert(0, Some(seg_idx));
                    matches
                })
                .or_else(|| {
                    let mut matches = inner(segments, seg_idx, route)?;
                    matches.optionals.insert(0, None);
                    Some(matches)
                }),
            // A splat captures the whole rest of the path, which can be empty.
            PathSegment::Splat(_) => Some(LocalizedPathMatch {
                splat: seg_idx,
                ..Default::default()
            }),
        }
    }

    inner(segments, 0, old_segments)
}

/// Strip `prefix` from the front of `path`, but only if `prefix` covers whole path segments.
///
/// Surrounding `/` are insignificant on both sides, so `"foo"`, `"/foo"`, `"foo/"` and `"/foo/"`
/// are all equivalent prefixes. Returns `None` if `path` is not under `prefix`, notably when they
/// only share a string prefix that stops in the middle of a segment (`"/foobar"` is not under
/// `"/foo"`). The returned remainder never starts with a `/`.
fn strip_path_prefix<'a>(path: &'a str, prefix: &str) -> Option<&'a str> {
    let prefix = prefix.trim_matches('/');
    let path = path.trim_start_matches('/');
    if prefix.is_empty() {
        return Some(path);
    }
    let rest = path.strip_prefix(prefix)?;
    match rest.as_bytes().first() {
        None => Some(rest),
        Some(b'/') => Some(rest.trim_start_matches('/')),
        // the prefix ended in the middle of a segment, `path` is not under `prefix`
        Some(_) => None,
    }
}

/// Return the first path segment of `path` located after `base_path`,
/// or `None` if `path` is not under `base_path`.
fn get_path_locale_segment<'a>(path: &'a str, base_path: &str) -> Option<&'a str> {
    let stripped_path = strip_path_prefix(path, base_path)?;
    let (to_match, _) = stripped_path.split_once('/').unwrap_or((stripped_path, ""));
    Some(to_match)
}

fn get_locale_from_path<L: Locale>(path: &str, base_path: &str) -> Option<L> {
    let to_match = get_path_locale_segment(path, base_path)?;
    L::get_all()
        .iter()
        .copied()
        .find(|l| l.as_str() == to_match)
}

fn construct_path_segments<'b, 'p: 'b>(
    segments: &[&'p str],
    new_segments: &'p [PathSegment],
    path_builder: &mut PathBuilder<'b>,
    matches: &LocalizedPathMatch,
) {
    let mut params = matches.params.iter();
    let mut optionals = matches.optionals.iter();

    for seg in new_segments {
        match seg {
            PathSegment::Unit => {}
            PathSegment::Param(_) => {
                if let Some(&seg_idx) = params.next() {
                    path_builder.push(segments[seg_idx]);
                }
            }
            PathSegment::OptionalParam(_) => {
                if let Some(&Some(seg_idx)) = optionals.next() {
                    path_builder.push(segments[seg_idx]);
                }
            }
            PathSegment::Static(to_push) => {
                path_builder.push(to_push);
            }
            PathSegment::Splat(_) => {
                let iter = segments[matches.splat..].iter().copied();
                path_builder.extend(iter);
                break;
            }
        }
    }
}

fn localize_path<'b, 'p: 'b>(
    path: &'p str,
    old_locale_segments: &[Vec<PathSegment>],
    new_locale_segments: &'p [Vec<PathSegment>],
    path_builder: &mut PathBuilder<'b>,
) -> bool {
    let path_segments = path
        .split('/')
        .filter(|s| !s.is_empty())
        .collect::<Vec<_>>();

    let res = old_locale_segments
        .iter()
        .enumerate()
        .find_map(|(pos, old_segments)| {
            match_path_segments(&path_segments, old_segments).map(|op| (pos, op))
        });

    let Some((pos, path_matches)) = res else {
        return false;
    };

    let new_segments = &new_locale_segments[pos];

    construct_path_segments(&path_segments, new_segments, path_builder, &path_matches);

    true
}

/// Rewrite `path_name` for a new locale.
///
/// This is the pure part of [`get_new_path`]: `old_locale_prefix` is the locale prefix currently
/// present in the URL (`None` if there is none), and `new_locale_prefix` is the one to put in the
/// new URL (`None` for the default locale, which is not prefixed).
fn localize_pathname<'a>(
    path_name: &'a str,
    base_path: &'a str,
    new_locale_prefix: Option<&'a str>,
    old_locale_prefix: Option<&str>,
    old_locale_segments: Option<&[Vec<PathSegment>]>,
    new_locale_segments: Option<&'a [Vec<PathSegment>]>,
) -> String {
    let mut path_builder = PathBuilder::default();
    path_builder.push(base_path);
    if let Some(new_locale_prefix) = new_locale_prefix {
        path_builder.push(new_locale_prefix);
    }
    if let Some(path_rest) = strip_path_prefix(path_name, base_path) {
        let path_rest = match old_locale_prefix {
            None => path_rest,
            // if the prefix is not there the URL is not localized, keep the path as is.
            Some(l) => strip_path_prefix(path_rest, l).unwrap_or(path_rest),
        };

        let localized = match (old_locale_segments, new_locale_segments) {
            (Some(old_locale_segments), Some(new_locale_segments)) => localize_path(
                path_rest,
                old_locale_segments,
                new_locale_segments,
                &mut path_builder,
            ),
            _ => false,
        };

        if !localized {
            path_builder.push(path_rest);
        }

        // else ?
    }
    path_builder.build()
}

fn get_new_path<L: Locale>(
    location: &Location,
    base_path: &str,
    new_locale: L,
    locale: Option<L>,
    segments: &RouteSegments<L>,
) -> String {
    let mut new_path = location.pathname.with_untracked(|path_name| {
        localize_pathname(
            path_name,
            base_path,
            (new_locale != L::default()).then(|| new_locale.as_str()),
            locale.map(Locale::as_str),
            segments.get(&locale.unwrap_or_default()).map(Vec::as_slice),
            segments.get(&new_locale).map(Vec::as_slice),
        )
    });

    location.search.with_untracked(|search| {
        if !search.is_empty() {
            new_path.push('?');
            new_path.push_str(search);
        }
    });
    location.hash.with_untracked(|hash| {
        if !hash.is_empty() {
            // Remove leading '#' if present
            let hash = hash.trim_start_matches('#');
            new_path.push('#');
            new_path.push_str(hash);
        }
    });
    new_path
}

/// State shared between the effects to absorb a browser history navigation.
///
/// We step out of the Leptos routes reactivity, so we don't get forward and backward history
/// change triggers and have to handle them manually. On a history change the URL is the source of
/// truth: the locale is updated to follow it, and neither effect must navigate in reaction.
///
/// Both flags are armed by [`check_history_change`] and each is consumed by exactly one effect.
/// They are only armed when the locale actually changes, because that is the only case where the
/// effects re-run to consume them, and each is consumed on every path of its effect: a flag left
/// armed would swallow the next locale switch, or rewrite the URL of the next navigation back to
/// the previous locale.
struct HistoryChange<L> {
    /// Locale of the URL navigated to, consumed by [`update_path_effect`].
    locale: Cell<Option<L>>,
    /// Whether the pending pathname change comes from the history,
    /// consumed by [`correct_locale_prefix_effect`].
    pending: Cell<bool>,
}

impl<L: PartialEq> HistoryChange<L> {
    fn new() -> Self {
        HistoryChange {
            locale: Cell::new(None),
            pending: Cell::new(false),
        }
    }

    /// Record a history navigation to a URL holding `path_locale`, the application currently being
    /// on `current_locale`. Returns `true` if the locale must be updated to follow the URL.
    fn record(&self, current_locale: L, path_locale: L) -> bool {
        if current_locale == path_locale {
            // The locale signal is not going to change, so the effects won't re-run to consume the
            // flags, and arming them would leave them armed for an unrelated future change.
            return false;
        }
        self.locale.set(Some(path_locale));
        self.pending.set(true);
        true
    }

    /// Consume the locale of a pending history navigation.
    fn take_locale(&self) -> Option<L> {
        self.locale.take()
    }

    /// Consume the pending history navigation flag.
    fn take(&self) -> bool {
        self.pending.replace(false)
    }
}

/// navigate to a new path when the locale changes
fn update_path_effect<L: Locale>(
    i18n: I18nContext<L>,
    base_path: &'static str,
    history: Rc<HistoryChange<L>>,
    segments: Arc<RouteSegments<L>>,
) -> impl Fn(Option<L>) -> L + 'static {
    let location = use_location();
    let navigate = use_navigate();
    move |prev_loc: Option<L>| {
        let path_locale = location
            .pathname
            .with_untracked(|path| get_locale_from_path::<L>(path, base_path));
        let new_locale = i18n.get_locale();
        // don't react on history change, the URL is already the one we want.
        if let Some(new_locale) = history.take_locale() {
            return new_locale;
        }
        let Some(prev_loc) = prev_loc else {
            return new_locale;
        };
        if new_locale == prev_loc || new_locale == path_locale.unwrap_or_default() {
            return new_locale;
        }

        let new_path = get_new_path(&location, base_path, new_locale, Some(prev_loc), &segments);

        let navigate = navigate.clone();

        // TODO FIXME: see https://github.com/leptos-rs/leptos/issues/2979
        // It works for now, but it is not ideal.
        request_animation_frame(move || {
            navigate(
                &new_path,
                NavigateOptions {
                    resolve: false,
                    scroll: false,
                    ..Default::default()
                },
            );
        });

        new_locale
    }
}

fn correct_locale_prefix_effect<L: Locale>(
    i18n: I18nContext<L>,
    base_path: &'static str,
    segments: Arc<RouteSegments<L>>,
    history: Rc<HistoryChange<L>>,
) -> impl Fn(Option<()>) + 'static {
    let location = use_location();
    let navigate = use_navigate();
    move |_| {
        let path_locale = location
            .pathname
            .with(|path| get_locale_from_path::<L>(path, base_path));
        let current_locale = i18n.get_locale_untracked();

        // consume it even when returning early, this pathname change is the one it was armed for.
        let history_changed = history.take();

        if current_locale == path_locale.unwrap_or_default() {
            return;
        }

        let new_locale = if history_changed {
            current_locale
        } else {
            path_locale.unwrap_or(current_locale)
        };

        let new_path = get_new_path(&location, base_path, new_locale, path_locale, &segments);

        let navigate = navigate.clone();

        i18n.set_locale(new_locale);

        // TODO FIXME: see https://github.com/leptos-rs/leptos/issues/2979
        // It works for now, but it is not ideal.
        request_animation_frame(move || {
            navigate(
                &new_path,
                NavigateOptions {
                    resolve: false,
                    replace: true,
                    scroll: false,
                    ..Default::default()
                },
            );
        });
    }
}

fn check_history_change<L: Locale>(
    i18n: I18nContext<L>,
    base_path: &'static str,
    history: Rc<HistoryChange<L>>,
) -> impl Fn(ev::PopStateEvent) + 'static {
    let location = use_location();

    move |_| {
        let path_locale = location
            .pathname
            .with_untracked(|path| get_locale_from_path::<L>(path, base_path).unwrap_or_default());

        if history.record(i18n.get_locale_untracked(), path_locale) {
            i18n.set_locale(path_locale);
        }
    }
}

fn maybe_redirect<L: Locale>(
    previously_resolved_locale: L,
    base_path: &str,
    segments: &RouteSegments<L>,
) -> Option<String> {
    let location = use_location();
    if cfg!(not(feature = "ssr")) || previously_resolved_locale == L::default() {
        return None;
    }
    let new_path = get_new_path(
        &location,
        base_path,
        previously_resolved_locale,
        None,
        segments,
    );
    Some(new_path)
}

#[derive(Clone)]
struct ViewWrapper<T, A, B>(T)
where
    T: Fn() -> Either<A, B> + Send + Clone + 'static,
    A: ChooseView,
    B: ChooseView;

impl<T, A, B> ChooseView for ViewWrapper<T, A, B>
where
    T: Fn() -> Either<A, B> + Send + Clone + 'static,
    A: ChooseView,
    B: ChooseView,
{
    fn choose(self) -> impl Future<Output = AnyView> {
        let inner = self.0();
        ChooseView::choose(inner)
    }

    async fn preload(&self) {}
}

fn view_wrapper<L, View>(
    view: View,
    route_locale: Option<L>,
    base_path: &'static str,
    segments: Arc<RouteSegments<L>>,
) -> Either<View, impl ChooseView>
where
    L: Locale,
    View: ChooseView,
{
    let i18n = use_i18n_context::<L>();

    let previously_resolved_locale = i18n.get_locale_untracked();

    // By precedence if there is a locale prefix in the URL it takes priority.
    // if there is none, use the one computed beforehand.

    let redir = if let Some(locale) = route_locale {
        i18n.set_locale(locale);
        None
    } else {
        maybe_redirect(previously_resolved_locale, base_path, &segments)
    };

    // Changing the locale on a history change would trigger the locale change effect, causing to
    // change the URL again but with a wrong previous locale, so this state syncs the effects
    // together on what is the locale currently in the URL.
    // It starts unarmed such that on the first render the effects don't change the locale instantly.
    let history = Rc::new(HistoryChange::new());

    Effect::new(update_path_effect(
        i18n,
        base_path,
        history.clone(),
        segments.clone(),
    ));

    // listen for history changes
    let handle = window_event_listener(
        ev::popstate,
        check_history_change(i18n, base_path, history.clone()),
    );

    on_cleanup(move || handle.remove());

    // correct the url when using <a> that removes the locale prefix
    Effect::new(correct_locale_prefix_effect(
        i18n, base_path, segments, history,
    ));

    match redir {
        None => Either::Left(view),
        Some(path) => {
            let view = move || view! { <Redirect path=path.clone() /> };
            Either::Right(view)
        }
    }
}

#[doc(hidden)]
pub fn i18n_routing<L: Locale, View, Chil>(
    base_path: &'static str,
    children: RouteChildren<Chil>,
    ssr_mode: SsrMode,
    view: View,
) -> impl MatchNestedRoutes + Clone
where
    View: ChooseView + Clone,
    Chil: MatchNestedRoutes + Clone + 'static,
{
    let children = children.into_inner();
    let base_route = NestedRoute::new(StaticSegment(""), view)
        .ssr_mode(ssr_mode)
        .child(children);

    let segments = generate_routes_for_each_locale::<L, _, _>(&base_route);

    I18nNestedRoute::new(base_path, base_route, Arc::new(segments))
}

type RouteSegments<L> = HashMap<L, Vec<Vec<PathSegment>>>;

#[derive(Clone)]
struct I18nNestedRoute<L, View, Chil> {
    route: BaseRoute<View, Chil>,
    base_path: &'static str,
    segments: Arc<RouteSegments<L>>,
}

impl<L, View, Chil> I18nNestedRoute<L, View, Chil> {
    pub fn new(
        base_path: &'static str,
        route: BaseRoute<View, Chil>,
        segments: Arc<RouteSegments<L>>,
    ) -> Self {
        Self {
            route,
            base_path,
            segments,
        }
    }
}

// what you will see after this comment is a bit of a hack.
// The goal here is to create N + 1 routes where N is the number of locales (last being for empty).
// not very difficult.
// but if you do it the "normal" way, changing locales will rebuild the entire tree, making the application
// lose state when it doesn't need to.
// So, we want to create N + 1 routes that are "the same".
// Leptos differentiates them with their "RouteId".
// So we basically create N+1 routes with the same route id.
// All the complexity you will see under this comment is done just to achieve this.

#[doc(hidden)]
pub type BaseRoute<View, Chil> = NestedRoute<StaticSegment<&'static str>, Chil, (), View>;

thread_local! {
    static CURRENT_ROUTE_LOCALE: RefCell<Option<&'static str>> = const { RefCell::new(None) };
}

fn set_current_route_locale<L: Locale>(new_locale: L) {
    CURRENT_ROUTE_LOCALE.with_borrow_mut(|locale| {
        *locale = Some(new_locale.as_str());
    })
}

fn reset_current_route_locale() {
    CURRENT_ROUTE_LOCALE.with_borrow_mut(|locale| *locale = None);
}

fn get_current_route_locale<L: Locale>() -> L {
    CURRENT_ROUTE_LOCALE
        .with_borrow(|locale| locale.as_ref().and_then(|locale| L::from_str(locale).ok()))
        .unwrap_or_default()
}

#[doc(hidden)]
pub struct I18nRouteMatch<L, View, Chil>
where
    Chil: MatchNestedRoutes + 'static,
    Chil::Match: MatchParams,
    View: ChooseView + Clone,
{
    locale: Option<L>,
    base_path: &'static str,
    matched: String,
    inner_match: <BaseRoute<View, Chil> as MatchNestedRoutes>::Match,
    segments: Arc<RouteSegments<L>>,
}

impl<L, View, Chil> MatchParams for I18nRouteMatch<L, View, Chil>
where
    Chil: MatchNestedRoutes + 'static,
    Chil::Match: MatchParams,
    View: ChooseView + Clone,
{
    fn to_params(&self) -> Vec<(std::borrow::Cow<'static, str>, String)> {
        MatchParams::to_params(&self.inner_match)
    }
}

impl<L, View, Chil> MatchInterface for I18nRouteMatch<L, View, Chil>
where
    L: Locale,
    Chil: MatchNestedRoutes + 'static,
    Chil::Match: MatchParams,
    View: ChooseView + Clone,
{
    type Child = <<BaseRoute<View, Chil> as MatchNestedRoutes>::Match as MatchInterface>::Child;

    fn as_id(&self) -> leptos_router::RouteMatchId {
        MatchInterface::as_id(&self.inner_match)
    }

    fn as_matched(&self) -> &str {
        &self.matched
    }

    fn into_view_and_child(self) -> (impl ChooseView, Option<Self::Child>) {
        let (view, child) = MatchInterface::into_view_and_child(self.inner_match);
        let new_view = move || {
            view_wrapper(
                view.clone(),
                self.locale,
                self.base_path,
                self.segments.clone(),
            )
        };
        (ViewWrapper(new_view), child)
    }
}

impl<L: Locale, View, Chil> MatchNestedRoutes for I18nNestedRoute<L, View, Chil>
where
    Chil: MatchNestedRoutes + 'static,
    Chil::Match: MatchParams,
    View: ChooseView + Clone,
{
    type Data = ();

    type Match = I18nRouteMatch<L, View, Chil>;

    fn match_nested<'a>(
        &'a self,
        path: &'a str,
    ) -> (Option<(leptos_router::RouteMatchId, Self::Match)>, &'a str) {
        let res = L::get_all()
            .iter()
            .copied()
            .find_map(|locale| {
                set_current_route_locale(locale);
                StaticSegment(locale.as_str())
                    .test(path)
                    .and_then(|partial_path_match| {
                        let remaining = partial_path_match.remaining();
                        let matched = partial_path_match.matched();
                        let (inner_match, remaining) =
                            MatchNestedRoutes::match_nested(&self.route, remaining);
                        let (route_match_id, inner_match) = inner_match?;
                        let matched = matched.to_string();
                        let route_match = I18nRouteMatch {
                            locale: Some(locale),
                            matched,
                            inner_match,
                            base_path: self.base_path,
                            segments: self.segments.clone(),
                        };
                        Some((Some((route_match_id, route_match)), remaining))
                    })
            })
            .or_else(|| {
                set_current_route_locale(L::default());
                let (inner_match, remaining) = MatchNestedRoutes::match_nested(&self.route, path);
                inner_match.map(|(route_match_id, inner_match)| {
                    let route_match = I18nRouteMatch {
                        locale: None,
                        matched: String::new(),
                        inner_match,
                        base_path: self.base_path,
                        segments: self.segments.clone(),
                    };
                    (Some((route_match_id, route_match)), remaining)
                })
            })
            .unwrap_or((None, path));
        reset_current_route_locale();
        res
    }

    fn generate_routes(&self) -> impl IntoIterator<Item = leptos_router::GeneratedRouteData> + '_ {
        let reset = std::iter::from_fn(|| {
            reset_current_route_locale();
            None
        });
        let default_locale_routes = std::iter::once_with(|| {
            set_current_route_locale(L::default());
            MatchNestedRoutes::generate_routes(&self.route)
                .into_iter()
                .map(|mut generated_route| {
                    // remove empty segment set by the inner route
                    generated_route.segments.remove(0);
                    generated_route
                })
        })
        .flatten();
        L::get_all()
            .iter()
            .copied()
            .flat_map(|locale| {
                set_current_route_locale(locale);
                MatchNestedRoutes::generate_routes(&self.route)
                    .into_iter()
                    .map(move |mut generated_route| {
                        if let Some(first) = generated_route.segments.first_mut() {
                            // replace the empty segment set by the inner route with the locale one
                            *first = PathSegment::Static(locale.as_str().into())
                        }
                        generated_route
                    })
            })
            .chain(default_locale_routes)
            .chain(reset)
    }

    fn optional(&self) -> bool {
        false
    }
}

fn generate_routes_for_each_locale<L, View, Chil>(route: &BaseRoute<View, Chil>) -> RouteSegments<L>
where
    L: Locale,
    View: ChooseView + Clone,
    Chil: MatchNestedRoutes + Clone + 'static,
{
    let mut segments = RouteSegments::default();

    for &locale in L::get_all() {
        set_current_route_locale(locale);
        let inner_segments: Vec<_> = MatchNestedRoutes::generate_routes(route)
            .into_iter()
            .map(|generated_route| generated_route.segments)
            .collect();

        segments.insert(locale, inner_segments);
    }

    reset_current_route_locale();

    segments
}

#[doc(hidden)]
#[derive(Clone, Copy)]
pub struct I18nPath<L, F> {
    func: F,
    marker: PhantomData<L>,
}

impl<L, F> Debug for I18nPath<L, F> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("I18nPath").finish()
    }
}

impl<L: Locale, F> I18nPath<L, F>
where
    F: Fn(L) -> &'static str,
{
    fn segments_for_current_locale(
        &self,
    ) -> impl Iterator<Item = leptos_router::StaticSegment<&'static str>> {
        let locale = get_current_route_locale::<L>();
        let s = (self.func)(locale);

        s.split('/')
            .filter(|p| !p.is_empty())
            .map(leptos_router::StaticSegment)
    }
}

impl<L: Locale, F> PossibleRouteMatch for I18nPath<L, F>
where
    F: Fn(L) -> &'static str,
{
    fn optional(&self) -> bool {
        false
    }

    fn test<'a>(&self, path: &'a str) -> Option<leptos_router::PartialPathMatch<'a>> {
        use leptos_router::PartialPathMatch;

        let mut segments = self.segments_for_current_locale().peekable();

        if segments.peek().is_none() {
            return ().test(path);
        }

        let mut remaining = path;
        let mut all_params = Vec::new();
        let mut matched_len = 0usize;

        for static_seg in segments {
            let pm = static_seg.test(remaining)?;

            let matched = pm.matched();
            matched_len += matched.len();
            remaining = pm.remaining();
            all_params.extend(pm.params());
        }

        Some(PartialPathMatch::new(
            remaining,
            all_params,
            &path[..matched_len],
        ))
    }

    fn generate_path(&self, path: &mut Vec<PathSegment>) {
        for static_seg in self.segments_for_current_locale() {
            static_seg.generate_path(path);
        }
    }
}

#[doc(hidden)]
pub fn make_i18n_path<L, F>(f: F) -> I18nPath<L, F>
where
    L: Locale,
    F: Fn(L) -> &'static str + Clone + 'static,
{
    I18nPath {
        func: f,
        marker: PhantomData,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    enum TestLocale {
        En,
        Fr,
    }

    fn seg(s: &'static str) -> PathSegment {
        PathSegment::Static(s.into())
    }

    /// Build a route the way `NestedRoute::generate_routes` does for the `I18nRoute` base route:
    /// the base route's own `StaticSegment("")` first, then the children segments.
    fn route(segments: &[PathSegment]) -> Vec<PathSegment> {
        let mut route = vec![seg("")];
        route.extend_from_slice(segments);
        route
    }

    #[test]
    fn strip_path_prefix_accepts_all_documented_base_path_forms() {
        for base_path in ["foo", "/foo", "foo/", "/foo/"] {
            assert_eq!(strip_path_prefix("/foo/about", base_path), Some("about"));
            assert_eq!(strip_path_prefix("/foo", base_path), Some(""));
            assert_eq!(strip_path_prefix("/foo/", base_path), Some(""));
        }
        for base_path in ["", "/"] {
            assert_eq!(strip_path_prefix("/about", base_path), Some("about"));
            assert_eq!(strip_path_prefix("/", base_path), Some(""));
        }
    }

    #[test]
    fn strip_path_prefix_requires_a_segment_boundary() {
        assert_eq!(strip_path_prefix("/foobar", "foo"), None);
        assert_eq!(strip_path_prefix("/fooen/x", "/foo"), None);
    }

    #[test]
    fn path_locale_segment_is_read_after_the_base_path() {
        assert_eq!(get_path_locale_segment("/foo/en/x", "foo"), Some("en"));
        assert_eq!(get_path_locale_segment("/en/x", "/"), Some("en"));
        assert_eq!(get_path_locale_segment("/", "/"), Some(""));
    }

    #[test]
    fn path_locale_segment_is_not_read_outside_of_the_base_path() {
        // `/fooen/x` is not under `/foo`, so there is no locale segment to find in it.
        assert_eq!(get_path_locale_segment("/fooen/x", "foo"), None);
        assert_eq!(get_path_locale_segment("/barfoo/en", "foo"), None);
    }

    #[test]
    fn old_locale_prefix_is_stripped_when_present() {
        let en = vec![route(&[seg("about")])];
        let fr = vec![route(&[seg("apropos")])];
        // on /fr/apropos, switching back to the default locale `en`
        let new_path =
            localize_pathname("/fr/apropos", "/", None, Some("fr"), Some(&fr), Some(&en));
        assert_eq!(new_path, "/about");
    }

    #[test]
    fn old_locale_prefix_is_only_stripped_on_a_segment_boundary() {
        let en = vec![route(&[seg("enroll")])];
        let fr = vec![route(&[seg("enroll")])];
        // on /enroll with the default locale `en` (so no prefix in the URL), switching to `fr`
        let new_path =
            localize_pathname("/enroll", "/", Some("fr"), Some("en"), Some(&en), Some(&fr));
        assert_eq!(new_path, "/fr/enroll");
    }

    #[test]
    fn every_documented_base_path_form_rewrites_the_same_url() {
        let en = vec![route(&[seg("about")])];
        let fr = vec![route(&[seg("about")])];
        for base_path in ["foo", "/foo", "foo/", "/foo/"] {
            // default locale -> `fr`
            let new_path = localize_pathname(
                "/foo/about",
                base_path,
                Some("fr"),
                Some("en"),
                Some(&en),
                Some(&fr),
            );
            assert_eq!(new_path, "/foo/fr/about", "base_path: {base_path:?}");

            // `fr` -> default locale
            let new_path = localize_pathname(
                "/foo/fr/about",
                base_path,
                None,
                Some("fr"),
                Some(&fr),
                Some(&en),
            );
            assert_eq!(new_path, "/foo/about", "base_path: {base_path:?}");
        }
    }

    #[test]
    fn base_path_is_only_stripped_on_a_segment_boundary() {
        // `/foobar` is not under the `/foo` base path, there is nothing to rewrite in it.
        let new_path = localize_pathname("/foobar", "/foo", Some("fr"), None, None, None);
        assert_eq!(new_path, "/foo/fr");
    }

    #[test]
    fn a_route_made_of_zero_width_segments_matches_the_root_path() {
        // the `I18nRoute` base route contributes its own `StaticSegment("")`, so an index route
        // mounted at the root of the application is only made of zero width segments.
        assert!(match_path_segments(&[], &route(&[])).is_some());
        assert!(match_path_segments(&[], &route(&[seg("")])).is_some());
        assert!(match_path_segments(&["about"], &route(&[seg("about"), seg("")])).is_some());
    }

    #[test]
    fn absent_optional_param_still_matches() {
        // `path!("users/:id?")` matches /users, so localizing /users must match it too.
        let users = route(&[seg("users"), PathSegment::OptionalParam("id".into())]);
        assert!(match_path_segments(&["users"], &users).is_some());
    }

    #[test]
    fn catch_all_matching_zero_segments_is_localized() {
        // `path!("files/*any")` matches /files, so localizing /files must match it too.
        let en = vec![route(&[seg("files"), PathSegment::Splat("any".into())])];
        let fr = vec![route(&[seg("fichiers"), PathSegment::Splat("any".into())])];
        let new_path =
            localize_pathname("/files", "/", Some("fr"), Some("en"), Some(&en), Some(&fr));
        assert_eq!(new_path, "/fr/fichiers");
    }

    #[test]
    fn optional_param_captures_the_path_value() {
        // `path!("users/:id?")` matches /users/42, so localizing /users/42 must match it too,
        // and keep the captured value.
        let en = vec![route(&[
            seg("users"),
            PathSegment::OptionalParam("id".into()),
        ])];
        let fr = vec![route(&[
            seg("utilisateurs"),
            PathSegment::OptionalParam("id".into()),
        ])];
        let new_path = localize_pathname(
            "/users/42",
            "/",
            Some("fr"),
            Some("en"),
            Some(&en),
            Some(&fr),
        );
        assert_eq!(new_path, "/fr/utilisateurs/42");

        let new_path =
            localize_pathname("/users", "/", Some("fr"), Some("en"), Some(&en), Some(&fr));
        assert_eq!(new_path, "/fr/utilisateurs");
    }

    #[test]
    fn optional_param_backtracks_when_absent() {
        // `path!("users/:id?/posts")`
        let users = route(&[
            seg("users"),
            PathSegment::OptionalParam("id".into()),
            seg("posts"),
        ]);

        let matches = match_path_segments(&["users", "posts"], &users).unwrap();
        assert_eq!(matches.optionals, [None]);

        let matches = match_path_segments(&["users", "42", "posts"], &users).unwrap();
        assert_eq!(matches.optionals, [Some(1)]);
    }

    #[test]
    fn a_route_longer_than_the_path_does_not_match() {
        let users = route(&[seg("users"), seg("list")]);
        assert!(match_path_segments(&["users"], &users).is_none());
        let user = route(&[seg("users"), PathSegment::Param("id".into())]);
        assert!(match_path_segments(&["users"], &user).is_none());
    }

    #[test]
    fn a_history_change_keeping_the_locale_arms_nothing() {
        // back/forward between two pages of the same locale: the locale signal doesn't change,
        // so no effect re-runs and nothing must be left armed for a later locale switch.
        let history = HistoryChange::new();
        assert!(!history.record(TestLocale::En, TestLocale::En));
        assert_eq!(history.take_locale(), None);
        assert!(!history.take());
    }

    #[test]
    fn a_history_change_switching_locale_is_consumed_once() {
        let history = HistoryChange::new();
        assert!(history.record(TestLocale::En, TestLocale::Fr));

        // both effects re-run and consume their flag
        assert_eq!(history.take_locale(), Some(TestLocale::Fr));
        assert!(history.take());

        // nothing is left for an unrelated later locale switch or navigation
        assert_eq!(history.take_locale(), None);
        assert!(!history.take());
    }
}
