name: Restore CI Environment
description: Restore prebuilt Rust toolchain and dependencies

runs:
  using: "composite"
  steps:
    - name: Download prepared cargo environment
      uses: actions/download-artifact@v4
      with:
        name: cargo-env

    - name: Download prepared target environment
      uses: actions/download-artifact@v4
      with:
        name: target-env

    - name: Extract cargo environment
      shell: bash
      run: tar -xzf cargo.tar.gz -C $HOME

    - name: Extract target environment
      shell: bash
      run: tar -xzf target.tar.gz
