name: Tests

on:
  push:
    branches: [master, next]
  pull_request:
    branches: [master, next]

env:
  CARGO_TERM_COLOR: always

jobs:
  ########################################
  # LIB TEST
  ########################################
  lib_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      # Setup Rust + Node + Playwright caches
      - uses: ./.github/actions/setup-ci

      - name: Run clippy
        working-directory: leptos_i18n
        run: cargo all-features clippy

      - name: Test all features
        working-directory: leptos_i18n
        run: cargo all-features test

      - name: Check format
        run: cargo fmt --check

  ########################################
  # SSR EXAMPLES
  ########################################
  test_ssr_examples:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        example:
          [
            hello_world_actix,
            hello_world_axum,
            workspace,
            axum_island,
            routing_ssr,
          ]

    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/setup-ci
        with:
          example_path: examples/ssr/${{ matrix.example }}

      - name: Build example
        working-directory: examples/ssr/${{ matrix.example }}
        run: cargo leptos build

      - name: Install Playwright
        working-directory: examples/ssr/${{ matrix.example }}
        run: |
          npm install
          npx playwright install --with-deps

      - name: Run e2e
        id: e2e
        working-directory: examples/ssr/${{ matrix.example }}
        run: npx playwright test

      - name: Upload e2e report
        if: ${{ steps.e2e.outcome == 'failure' && !cancelled() }}
        uses: actions/upload-artifact@v6
        with:
          name: playwright-report-${{ matrix.example }}
          path: examples/ssr/${{ matrix.example }}/playwright-report/

  ########################################
  # DYNAMIC SSR EXAMPLES
  ########################################
  test_ssr_dyn_load_examples:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        example: [hello_world_actix, hello_world_axum, axum_island, namespaces]

    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/setup-ci
        with:
          example_path: examples/dynamic_load/${{ matrix.example }}

      - name: Build example
        working-directory: examples/dynamic_load/${{ matrix.example }}
        run: cargo leptos build

      - name: Install Playwright
        working-directory: examples/dynamic_load/${{ matrix.example }}
        run: |
          npm install
          npx playwright install --with-deps

      - name: Run e2e
        id: e2e
        run: npx playwright test
        working-directory: examples/dynamic_load/${{ matrix.example }}

      - name: Upload e2e report
        if: ${{ steps.e2e.outcome == 'failure' && !cancelled() }}
        uses: actions/upload-artifact@v6
        with:
          name: playwright-report-${{ matrix.example }}
          path: examples/dynamic_load/${{ matrix.example }}/playwright-report/

  ########################################
  # CSR EXAMPLES
  ########################################
  test_csr_examples:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        example:
          [
            counter,
            counter_icu_datagen,
            counter_plurals,
            interpolation,
            namespaces,
            subkeys,
            yaml,
            routing_csr,
            subcontext,
            custom_formatter,
          ]

    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/setup-ci
        with:
          example_path: examples/csr/${{ matrix.example }}

      - name: Build example
        working-directory: examples/csr/${{ matrix.example }}
        run: trunk build

      - name: Install Playwright
        working-directory: examples/csr/${{ matrix.example }}
        run: |
          npm install
          npx playwright install --with-deps

      - name: Run e2e
        id: e2e
        run: npx playwright test
        working-directory: examples/csr/${{ matrix.example }}

      - name: Upload e2e report
        if: ${{ steps.e2e.outcome == 'failure' && !cancelled() }}
        uses: actions/upload-artifact@v6
        with:
          name: playwright-report-${{ matrix.example }}
          path: examples/csr/${{ matrix.example }}/playwright-report/

  ########################################
  # TEST SUITES
  ########################################
  test_suite:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        suite: [json, json5, yaml, toml, namespaces]

    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/setup-ci

      - name: Run test suite
        working-directory: tests/${{ matrix.suite }}
        run: cargo test
