name: Tests

on:
  push:
    branches: [master, next]
  pull_request:
    branches: [master, next]

env:
  CARGO_TERM_COLOR: always

jobs:
  ########################################
  # LIB TEST
  ########################################
  lib_test:
    name: Test leptos_i18n package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Setup
        uses: ./.github/actions/setup-ci
        with:
          rust_toolchain: "nightly"

      - name: Run clippy
        working-directory: leptos_i18n
        run: cargo all-features clippy

      - name: Test all features
        working-directory: leptos_i18n
        run: cargo all-features test

      - name: Check format
        run: cargo fmt --check

  ########################################
  # SSR EXAMPLES
  ########################################
  test_ssr_examples:
    name: Test ${{ matrix.example }} SSR example
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        example:
          [
            hello_world_actix,
            hello_world_axum,
            workspace,
            axum_island,
            routing_ssr,
          ]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Setup
        uses: ./.github/actions/setup-ci
        with:
          example_path: examples/ssr/${{ matrix.example }}

      - name: Build example
        working-directory: examples/ssr/${{ matrix.example }}
        run: cargo leptos build

      - name: Run e2e
        id: e2e
        working-directory: examples/ssr/${{ matrix.example }}
        run: npx playwright test

      - name: Upload e2e report
        if: ${{ steps.e2e.outcome == 'failure' && !cancelled() }}
        uses: actions/upload-artifact@v6
        with:
          name: playwright-report-${{ matrix.example }}
          path: examples/ssr/${{ matrix.example }}/playwright-report/

  ########################################
  # SSR DYN LOAD EXAMPLES
  ########################################
  test_ssr_dyn_load_examples:
    name: Test ${{ matrix.example }} dyn load SSR example
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        example: [hello_world_actix, hello_world_axum, axum_island, namespaces]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Setup
        uses: ./.github/actions/setup-ci
        with:
          example_path: examples/dynamic_load/${{ matrix.example }}

      - name: Build example
        working-directory: examples/dynamic_load/${{ matrix.example }}
        run: cargo leptos build

      - name: Run e2e
        id: e2e
        run: npx playwright test
        working-directory: examples/dynamic_load/${{ matrix.example }}

      - name: Upload e2e report
        if: ${{ steps.e2e.outcome == 'failure' && !cancelled() }}
        uses: actions/upload-artifact@v6
        with:
          name: playwright-report-${{ matrix.example }}
          path: examples/dynamic_load/${{ matrix.example }}/playwright-report/

  ########################################
  # CSR DYN LOAD EXAMPLES
  ########################################

  test_csr_dyn_load_examples:
    name: Test ${{ matrix.example }} dyn load CSR example
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        example: [csr_counter]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Setup
        uses: ./.github/actions/setup-ci
        with:
          example_path: examples/dynamic_load/${{ matrix.example }}

        # FIXME: This step is due to the fact that `trunk build` call the build script after the asset pipeline
        # So the translations generated by it are not found and cause an error
        # We thus use `cargo build` to run the build script once before `trunk build`.
      - name: "Pre-Build ${{ matrix.example }} example"
        working-directory: examples/dynamic_load/${{ matrix.example }}
        run: cargo build

      - name: Build example
        working-directory: examples/dynamic_load/${{ matrix.example }}
        run: trunk build

      - name: Run e2e
        id: e2e
        run: npx playwright test
        working-directory: examples/dynamic_load/${{ matrix.example }}

      - name: Upload e2e report
        if: ${{ steps.e2e.outcome == 'failure' && !cancelled() }}
        uses: actions/upload-artifact@v6
        with:
          name: playwright-report-${{ matrix.example }}
          path: examples/dynamic_load/${{ matrix.example }}/playwright-report/

  ########################################
  # CSR EXAMPLES
  ########################################
  test_csr_examples:
    name: Test ${{ matrix.example }} CSR example
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        example:
          [
            counter,
            counter_icu_datagen,
            counter_plurals,
            interpolation,
            namespaces,
            subkeys,
            yaml,
            routing_csr,
            subcontext,
            custom_formatter,
          ]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Setup
        uses: ./.github/actions/setup-ci
        with:
          example_path: examples/csr/${{ matrix.example }}

      - name: Build example
        working-directory: examples/csr/${{ matrix.example }}
        run: trunk build

      - name: Run e2e
        id: e2e
        run: npx playwright test
        working-directory: examples/csr/${{ matrix.example }}

      - name: Upload e2e report
        if: ${{ steps.e2e.outcome == 'failure' && !cancelled() }}
        uses: actions/upload-artifact@v6
        with:
          name: playwright-report-${{ matrix.example }}
          path: examples/csr/${{ matrix.example }}/playwright-report/

  ########################################
  # TEST SUITES
  ########################################
  test_suite:
    name: Test suite ${{ matrix.suite }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        suite: [json, json5, yaml, toml, namespaces]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Setup
        uses: ./.github/actions/setup-ci

      - name: Run test suite
        working-directory: tests/${{ matrix.suite }}
        run: cargo test
